### ISSUE TITLE
Failed to interpret some npy's as a pickle

### ISSUE THREAD

**Issue by cuevhv** [hiroyasuakada/UnrealEgo#1]
Hi. Thanks a lot for the dataset.
I'm having troubles when opening some npy files with: `frame_data = np.load(frame_data_path, allow_pickle=True)`. The error I'm getting is "Failed to interpret file as a pickle".
The files where it fails are:
 
-DowntownWest_Demo_Environment/Day/rp_joko_rigged_003_ue4/SKM_MenReadingGlasses_Shape_01/003/Clean_And_Jerk/all_data_with_img-256_hm-64_pose-16_npy/frame_186.npy
-Maps_BigCompany/Day/rp_joyce_rigged_005_ue4/SKM_MenReadingGlasses_Shape_01/001/Cross_Jumps_Rotation/all_data_with_img-256_hm-64_pose-16_npy/frame_44.npy
-KyotoAlley_Showcase/Night/rp_maya_rigged_003_ue4/SKM_MenReadingGlasses_Shape_01/017/Lifting__1_/all_data_with_img-256_hm-64_pose-16_npy/frame_142.npy
-DowntownWest_Demo_Environment/Day/rp_eric_rigged_001_ue4/SKM_MenReadingGlasses_Shape_01/002/Dying__1_/all_data_with_img-256_hm-64_pose-16_npy/frame_38.npy
-CityPark_Showcase/Day/rp_carla_rigged_001_ue4/SKM_MenReadingGlasses_Shape_01/019/Tender_Placement__2_/all_data_with_img-256_hm-64_pose-16_npy/frame_110.npy
-DowntownWest_Demo_Environment/Day/rp_carla_rigged_001_ue4/SKM_MenReadingGlasses_Shape_01/023/Swing_Dancing__5_/all_data_with_img-256_hm-64_pose-16_npy/frame_11.npy
-KyotoAlley_Showcase/Day/rp_janna_rigged_002_ue4/SKM_MenReadingGlasses_Shape_01/001/Joyful_Jump__23_/all_data_with_img-256_hm-64_pose-16_npy/frame_40.npy
-SuburbNeighborhood_DemoMap_Day/Day/rp_maya_rigged_003_ue4/SKM_MenReadingGlasses_Shape_01/018/Right_Turn/all_data_with_img-256_hm-64_pose-16_npy/frame_24.npy

Perhaps those npy files got corrupted when uploaded to the google drive? I've downloaded them many times and they still can't be opened.

Many thanks.

**Comment by hiroyasuakada** [comment]
Thank you for your report, I’ll check them.

**Comment by hiroyasuakada** [comment]
Updated! Again, thank you for letting me know.
