### ISSUE TITLE
Body joints mapping with SMPL

### ISSUE THREAD

**Issue by qzane** [hiroyasuakada/UnrealEgo#10]
Hi, thanks for this great work about egocentric body pose estimation. I'm trying to fit SMPL body model to this dataset but I find the naming in the json file is very different from SMPL and SMPL-H model in [here](https://github.com/vchoutas/smplx/blob/main/smplx/joint_names.py). Could you kindly share the mapping between SMPL model or fitted SMPL parameters with me? Thank you so much!

**Comment by hiroyasuakada** [comment]
Hi, 

Our dataset is based on the default skeleton of UE4 (See our supplemental material for more details). We don't have the mapping function between our data and SMPL yet.
