### ISSUE TITLE
The ground truth visualization results of the skeleton

### ISSUE THREAD

**Issue by unparalleled-soul** [hiroyasuakada/UnrealEgo#12]
Hello，I have a question. How can I view the ground truth visualization results of the skeleton? I hope to receive your guidance, thank you！

**Comment by hiroyasuakada** [comment]
Hello, you can use Open3D for visualization.

For example, you can create sphere mesh for each joint and create line mesh for each bone between joints (with any colors).

**Comment by unparalleled-soul** [comment]
Thank you for your quick response.
