### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by reynoldscem** [hiroyasuakada/UnrealEgo#2]
Hi,

I unfortunately lost the data after having downloaded it. I am more interested in the metadata than the images. Would it be possible to provide a package of just the metadata and no images please?

**Comment by hiroyasuakada** [comment]
For internal reasons, I separated UnrealEgo into 2 different sets (See the current version of README). 

“UnrealEgo 01-06” contains original data, such as RGB images, Depth images, and JSON files (~1.2TB in total). 

“UnrealEgo impl 01-03” contains preprocessed NumPy files (~1TB in total), such as resized RGB images, 2D heatmaps, and pelvis-relative 3D keypoints, which can be used to try our implementations without downloading original data.

We might consider restructuring the dataset in the future.
