### ISSUE TITLE
Some questions regarding camera parameters and data normalization

### ISSUE THREAD

**Issue by akallen** [hiroyasuakada/UnrealEgo#5]
Hi,

I found there are camera parameters provided in the json file, like global translation and rotation. However, if I want to project the 3D points back to 2D space, we might still need the intrinsic matrix and also the distortion parameters (khmc and kd). Could you please provide a sample code to show how the 3D to 2D projection works?

My another question is that you mentioned the data in npy form is "normalized with ImageNet statistics". Could you elaborate more on that? Does it mean you apply "mean=[0.485, 0.456, 0.406] and std=[0.229, 0.224, 0.225]" to the raw data?

Thank you for your help on the clarification!

**Comment by hiroyasuakada** [comment]
Hi,

**1. Fisheye camera parameters**
I uploaded the file of calibration parameters [here](https://github.com/hiroyasuakada/UnrealEgo/blob/7d6c06f2a7c9ed27ba78d686bcff7b65fcf1fcca/utils/fisheye_calibration_UEP.json). 
We used the Scaramuzza fisheye camera model. Please take a look at [its official website](https://sites.google.com/site/scarabotix/ocamcalib-omnidirectional-camera-calibration-toolbox-for-matlab) for more details about the camera model and the projection.

**2. NPY data**
We first resized the image from 1024×1024 to 256×256 and normalized it with "mean=[0.485, 0.456, 0.406] and std=[0.229, 0.224, 0.225]". 

Hope this will help.

**Comment by akallen** [comment]
@hiroyasuakada Thank you for providing the calibration parameters. I am still having some doubts on how to project the 3D points back to 2D points. Even though I have tried with the ocamlib, the generated 2D result still looks weird. Could you take a look at my code/process to see if there is anything wrong?

```
## Coordinate conversion from Unreal Engine to OpenCV
Mue = np.array([[1, 0, 0, 0],
                [0, -1, 0, 0],
                [0, 0, 1, 0],
                [0, 0, 0, 1]])

## Camera transformation matrix
translation = np.array(data['camera_left']['trans'])
rotation = np.array(data['camera_left']['rot']) * np.pi / 180.0
Mf = transformations.euler_matrix(rotation[0],
                                  rotation[1],
                                  rotation[2],
                                  'sxyz')
Mf[0:3, 3] = translation
Mf = np.linalg.inv(Mf)
M = Mue.T.dot(Mf)

## Convert UE 3D points to Camera coordinate's 3D points
joints = np.vstack([data['joints'][j]['trans'] for j in data['joints'].keys()]).T
Xj = M[0:3, 0:3].dot(joints) + M[0:3, 3:4]

## Project to 2D points using ocam_model
ocam_model = get_ocam_model('calib_results.txt')
pts2d = world2cam(Xj, ocam_model)
```
The function of `get_ocam_model` and 'world2cam' are referred from [Python-Calibration](https://github.com/carlosferrazza/Python-Calibration)

The derived `pts2d` result doesn't match `camera_left_pts2d`, or even Xj is not the same with `camera_left_pts3d`. Did I miss something during the conversion process? Really appreciate your help on this.
