### ISSUE TITLE
Question on projecting 3D points back to 2D space

### ISSUE THREAD

**Issue by akallen** [hiroyasuakada/UnrealEgo#6]
Thank you for providing the calibration parameters. I am still having some doubts on how to project the 3D points back to 2D points with the provided calibration parameters. Even though I have tried with the ocamlib, the generated 2D result still looks weird. Could you take a look at my code/process to see if there is anything wrong?

```
## Coordinate conversion from Unreal Engine to OpenCV
Mue = np.array([[1, 0, 0, 0],
                [0, -1, 0, 0],
                [0, 0, 1, 0],
                [0, 0, 0, 1]])

## Camera transformation matrix
translation = np.array(data['camera_left']['trans'])
rotation = np.array(data['camera_left']['rot']) * np.pi / 180.0
Mf = transformations.euler_matrix(rotation[0],
                                  rotation[1],
                                  rotation[2],
                                  'sxyz')
Mf[0:3, 3] = translation
Mf = np.linalg.inv(Mf)
M = Mue.T.dot(Mf)

## Convert UE 3D points to Camera coordinate's 3D points
joints = np.vstack([data['joints'][j]['trans'] for j in data['joints'].keys()]).T
Xj = M[0:3, 0:3].dot(joints) + M[0:3, 3:4]

## Project to 2D points using ocam_model
ocam_model = get_ocam_model('calib_results.txt')
pts2d = world2cam(Xj, ocam_model)
```
The function of `get_ocam_model` and 'world2cam' are referred from [Python-Calibration](https://github.com/carlosferrazza/Python-Calibration)

The derived `pts2d` result doesn't match `camera_left_pts2d`, or even Xj is not the same with `camera_left_pts3d`. Did I miss something during the conversion process? Really appreciate your help on this.

**Comment by hiroyasuakada** [comment]
Hi, sorry for my late reply, I updated README with more info about the data format.

The UE4 uses a bit unusual coordinate system, *i.e.*, a left-handed coordinate system with z-up. [(reference)](https://www.mathworks.com/help/uav/ug/coordinate-systems-for-unreal-engine-simulation-in-uav-toolbox.html)

We first converted the UE4 data from a left-handed to a right-handed system and then obtained camera-relative data.

Please also try to visualize the RGB images with 3D-to-2D projections.

**Comment by akallen** [comment]
Thank you for your reply. I am not that familiar with the coordinate conversion and the process to derive 2D projected points in the OpenCV image space as I am relatively new in this field. 

Is it possible for you to shed some lights on providing an example starting from:

A joint's trans `(273.524,170.463, 90.392)` with camera's trans `(268.528, 146.558, 153.531)` and rot `(-89.743584, 107.73465, -12.102791)` to camera relative 3D position `(-7.377120887427383, -23.022828677846455, 63.233454824822076)` and the 2D points on the image `(455.1630859375, 336.2279968261719)`?

Those values are derived directly from one of the json file, and I couldn't figure out the relation between them even using the ocamlib. 

Sorry for asking many dumb questions and thank you so much for your patience.

**Comment by ChenhongyiYang** [comment]
Hi, you can compute the projection with the following function. (x, y, z) is the camera_left_pts3d in the annotation json file, and (u, v) is the camera_left_pts2d in the annotation json file. Of course this function also works for the right camera. 


```python
import math 

def project_to_image_plane(x, y, z):
    with open('./fisheye_calibration_UEP.json', 'r') as f:
        params = json.load(f)

    polynomialW2C = np.array(params['polynomialW2C'])  
    u0, v0 = params['image_center']  

    norm = math.sqrt(x*x + y*y)
    theta = math.atan(-z / norm)

    rho = sum(a * theta**i for i, a in enumerate(polynomialW2C))

    u = x / norm * rho + u0
    v = y / norm * rho + v0
    return u, v
```

**Comment by akallen** [comment]
@ChenhongyiYang Thank you for the clarification!
