### ISSUE TITLE
Coordinate system for GT 3D

### ISSUE THREAD

**Issue by ZhengyiLuo** [hiroyasuakada/UnrealEgo#7]
Thanks for the amazing work! 

I am wondering which coordinate system is the GT 3D computed in? The name "camera pts3d" seems to indicate the camera's coordinate system. If so, then which camera?

**Comment by hiroyasuakada** [comment]
We provide json files of "camera_left_pts3d" and camera_right_pts3d" in the opencv coordinate system.

**Comment by ZhengyiLuo** [comment]
I see! Thanks for the response! 

Which one is the model defaulting to? Left or right?

**Comment by hiroyasuakada** [comment]
Each joint data contains its 3D locations relative to both left and right cameras.

Our method estimates pelvis-relative joint positions (not relative to cameras). 

For "UnrealEgoData impl", we obtained the ground truths by subtracting the pelvis position from each joint position. 

Example:

>                 gt_pose_left = np.array([
>                     json_data["joints"][joint_name]["camera_left_pts3d"] for joint_name in list_joints
>                 ])
>                 gt_pose_left_pelvis = np.array(json_data["joints"]["pelvis"]["camera_left_pts3d"])
>                 gt_local_pose = gt_pose_left - gt_pose_left_pelvis
