### ISSUE TITLE
Download meta data

### ISSUE THREAD

**Issue by ChenhongyiYang** [hiroyasuakada/UnrealEgo#9]
Hi, 

I am wondering if there is any way to only download the .json metadata for each frame? 

Best,

**Comment by hiroyasuakada** [comment]
Hi, we are currently in the process of the dataset update. Users will be able to download only json files by the end of next month.

**Comment by Frank-F2022** [comment]
Hi, is the meta data available without downloading the full data now?

**Comment by hiroyasuakada** [comment]
Hi, the metadata of UnrealEgo2 data (a larger and more diverse version than UnrealEgo) is available without downloading the full data. See the relevant project page.

Due to my other tasks, unfortunately, I currently don't have time to reorganize UnrealEgo data.
